package com.example.convertlist.types.convert.equipment

data class EquipmentResult(
    val condition: String,
    val created_at: String,
    val created_by: Int,
    val created_date: String,
    val description: String,
    val disabled: Boolean,
    val equipment: Int,
    val equipment_name: String,
    val expiration_year: Int?,
    val fin_source: Int,
    val fin_source_name: String,
    val id: Int,
    val is_unique: Boolean,
    val lab: Int,
    val lab_name_ru: String,
    val lab_name_uz: String,
    val manufacture_country: Any?,
    val manufacture_year: Any?,
    val name: String,
    val organisation: Int,
    val organisation_name: String,
    val purchase_country: Any,
    val purchase_currency: Int,
    val purchase_currency_name: String,
    val purchase_price: Int,
    val purchase_reason: Any,
    val purchase_year: Int,
    val quantity: Int,
    val status: String,
    val stock_number: String,
    val tnved: Any,
    val updated_at: String,
    val updated_by: Int,
    val updated_date: String
)