package uz.project.labsconnect.data_type

data class ResultX(
    val condition: String,
    val created_at: String,
    val created_by: Int,
    val created_date: String,
    val description: String,
    val disabled: Boolean,
    val equipment: Int,
    val equipment_name: String,
    val expiration_year: Any?,
    val fin_source: Any,
    val id: Int,
    val is_unique: Boolean,
    val lab: Any,
    val manufacture_country: Int,
    val manufacture_country_name: String,
    val manufacture_year: Int?,
    val name: String,
    val organisation: Int,
    val organisation_name: String,
    val purchase_country: Int,
    val purchase_country_name: String,
    val purchase_currency: Int,
    val purchase_currency_name: String,
    val purchase_price: Int,
    val purchase_reason: Any,
    val purchase_year: Int,
    val quantity: Int,
    val status: String,
    val stock_number: String,
    val tnved: Any,
    val updated_at: String,
    val updated_by: Any,
    val updated_date: String
)